# Generated by Django 3.0.3 on 2020-05-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('genre', models.CharField(max_length=300)),
                ('duration', models.DurationField()),
                ('posterLink', models.TextField()),
                ('videoLink', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=10)),
            ],
        ),
    ]
